nats:
  replicas: 3 
  jetstream:
    enabled: true
    memStorage:
      enabled: true
    fileStorage:
      enabled: true
      storageSize: 10Gi 
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  port: 4222
